[package]
edition = "2021"
name = "notion2md"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.0"
chrono = {version = "0.4.1", features = ["serde"]}
futures = "0.3.24"
reqwest = {version = "0.11.11", features = ["json"]}
serde = {version = "1.0.144", features = ["derive"]}
tokio = {version = "1.20.1", features = ["full"]}
uuid = {version = "1.1.2", features = ["v4", "serde"]}
